meta_title: "DiveSitesFinder"
meta_description: "Find your next dive destination with ease."
meta_image: "seo/default_meta_image.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@"